# Generated by Django 4.2.5 on 2023-11-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='client_id',
            new_name='user_id',
        ),
    ]
