# Generated by Django 4.2.5 on 2023-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_belltask_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='belltask',
            name='status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in progress', max_length=20),
        ),
    ]
