# Generated by Django 4.2.5 on 2023-11-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_belltask_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belltask',
            name='value',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
